name 'ldapjs_crowd_server'
version '0.1.1'
description 'Deploy a ldapjs-crowd-server service'
maintainer 'Peter Halliday'
maintainer_email 'pghalliday@gmail.com'
source_url 'https://github.com/pghalliday-cookbooks/ldapjs-crowd-server'
issues_url 'https://github.com/pghalliday-cookbooks/ldapjs-crowd-server/issues'
supports 'ubuntu'
